### ISSUE TITLE
라벨 클릭시 체크박스 클릭 이벤트 발생 안함

### ISSUE THREAD

**Issue by Bhanjo** [mju-likelion/x-rated#16]
![캡처](https://user-images.githubusercontent.com/63037629/216363937-d77ae2a7-2c84-47a1-810b-598c09cf64e1.PNG)

체크박스 옆에 텍스트를 클릭해도 체크박스가 체크될 수 있도록 하면 좋을 것 같습니다!

button과 label을 조합해 이 방법을 쉽게 구현할 수 있습니다.

현재 텍스트는 `span`으로 되어있는데 이를 `label` 태그로 바꿔보세요! 혹은 `label for` 등을 검색하면 좀 더 자세한 내용을 알 수 있습니다.

**Comment by ChoiWonYu** [comment]
해결했습니다 감사합니다!
