### ISSUE TITLE
채널톡 height 영역 이슈

### ISSUE THREAD

**Issue by yhyem** [mju-likelion/x-rated#36]
![image](https://user-images.githubusercontent.com/65844764/218270184-250a2273-0422-460d-98e2-737409e00726.png)
![image](https://user-images.githubusercontent.com/65844764/218270378-d32b6ba8-32f3-47e9-bbaf-c76e25ecb9bf.png)

채널톡 영역 만큼 여백 증가

**Comment by rninzi** [comment]
이건 우리 둘이 함께하는 과제.

**Comment by yhyem** [comment]
1. position을 fixed로 고쳐서 푸터에도 그냥 겹치게 하기 (디자인팀 의도와 맞지않음)
2. 이미지 크기를 줄여서 이미지 높이까지 같이 계산하기 (모든 페이지 마진값 계산 다시필요)

**Comment by rninzi** [comment]
2번 방법으로` 기존 채널톡 파일 내부 위아래 여백 제외하고 그림부분만 이용하는 방식` 채택 땅땅

푸터와 채널톡 사이 margin은 채널톡 아이콘 내부 margin bottom줘서 해결했구
`각자 페이지에서 본인 콘텐츠와 채널톡 사이 margin이 필요하다 싶으면 margin bottom주는 방식`으로 가져가면 될 듯 합니다.

+) 채널톡에 margin top이나 위에 여백이 있으면 안 되는 이유가 지원 확인하기 페이지에서 버튼과 채널톡 기존 영역(여백있는 118*118)이 겹치는 바람에 애초에 제거해줘야 이슈 해결에 용이해서 번거롭더라도 각자 맡은 페이지 내에서 수정 요청드립니다!
이해가 어려우실 수도 있는데 피그마와 첨부된 사진 참고하시면 도움 되실거예용
![image](https://user-images.githubusercontent.com/90755664/218304720-bbe2c83f-4d2b-4677-84a7-8fc6b974de7c.png)
