### ISSUE TITLE
Main  페이지 UI 이슈

### ISSUE THREAD

**Issue by Bhanjo** [mju-likelion/x-rated#5]
![캡처](https://user-images.githubusercontent.com/63037629/214873037-18d22885-f2ba-4d31-8ce3-d31de401c897.PNG)

#### Issue
width >= 1500px 일 때 위 사진과 같이 `지원하기 버튼`과 `모집정보` UI가 맞지 않습니다!

**Comment by yhyem** [comment]
아직 반응형 미구현 상태입니다!!

**Comment by yhyem** [comment]
![image](https://user-images.githubusercontent.com/65844764/214932989-bb604b9c-8df6-411b-8391-93520d927f7f.png)

수정 완료하였습니다!
